# Generated by Django 4.1.2 on 2022-10-31 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_collection_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='movies',
        ),
        migrations.AddField(
            model_name='collection',
            name='movies',
            field=models.ManyToManyField(to='movie.movie'),
        ),
    ]
