# Generated by Django 4.1.2 on 2022-11-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_requestcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcount',
            name='request',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
